name: heart-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - scikit-learn
  - xgboost
  - tensorflow
  - shap
  - pip
  - pip:
    - scikeras